<?php

namespace Fabiang\Sasl\Authentication;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-05 at 13:23:19.
 *
 * @coversDefaultClass Fabiang\Sasl\Authentication\Anonymous
 */
class AnonymousTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Anonymous
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Anonymous;
    }

    /**
     * @covers ::getResponse
     */
    public function testGetResponse()
    {
        $this->assertSame('token', $this->object->getResponse('token'));
    }
}
