<?php

namespace Fabiang\Sasl\Authentication;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-05 at 13:42:51.
 *
 * @coversDefaultClass Fabiang\Sasl\Authentication\CramMD5
 */
class CramMD5Test extends \PHPUnit_Framework_TestCase
{

    /**
     * @var CramMD5
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CramMD5;
    }

    /**
     * @covers ::getResponse
     * @covers ::hmacMd5
     */
    public function testGetResponse()
    {
        $this->assertSame(
            'user 270af9c7234b7c03b0d5490360d8cad8',
            $this->object->getResponse('user', 'pass', 'challenge')
        );
    }
}
