<?php

namespace Fabiang\Sasl\Authentication;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-05 at 13:31:46.
 *
 * @coversDefaultClass Fabiang\Sasl\Authentication\External
 */
class ExternalTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var External
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new External;
    }

    /**
     * @covers Fabiang\Sasl\Authentication\External::getResponse
     */
    public function testGetResponse()
    {
        $this->assertSame('zid', $this->object->getResponse('user', 'pass', 'zid'));
    }
}
