<?php

namespace Fabiang\Sasl\Authentication;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-12-05 at 13:30:31.
 *
 * @coversDefaultClass Fabiang\Sasl\Authentication\Login
 */
class LoginTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Login
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Login;
    }

    /**
     * @covers ::getResponse
     */
    public function testGetResponse()
    {
        $this->assertSame('LOGIN user pass', $this->object->getResponse('user', 'pass'));
    }
}
